import http.server
import ssl
import json
import urllib.request
import re
from datetime import datetime

class MockGraphQLHandler(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        if self.path == "/graphql":
            self.handle_graphql()
        else:
            self.send_response(404)
            self.end_headers()
            
    def handle_graphql(self):
        # Read request body
        content_length = int(self.headers.get('Content-Length', 0))
        req_body = self.rfile.read(content_length).decode('utf-8')
        print(f"GraphQL request received: {req_body[:200]}...")
        
        # We will dynamically scrape the user's contributions page
        url = "https://github.com/users/justdarshan510/contributions"
        req = urllib.request.Request(
            url, 
            headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
        )
        try:
            with urllib.request.urlopen(req) as response:
                html = response.read().decode('utf-8')
            
            tooltips = re.findall(r'for="([^"]+)"[^>]*>([^<]+)', html)
            tooltip_map = {id_: content.strip() for id_, content in tooltips}
            
            days_matches = re.findall(r'<td[^>]*data-date="([^"]+)"[^>]*id="([^"]+)"[^>]*data-level="([^"]+)"', html)
            if not days_matches:
                days_matches = re.findall(r'<td[^>]*data-date="([^"]+)"[^>]*data-level="([^"]+)"[^>]*id="([^"]+)"', html)
                days_matches = [(d[0], d[2], d[1]) for d in days_matches]
                
            level_map = {
                "0": ("#ebedf0", "NONE"),
                "1": ("#9be9a8", "FIRST_QUARTILE"),
                "2": ("#40c463", "SECOND_QUARTILE"),
                "3": ("#30a14e", "THIRD_QUARTILE"),
                "4": ("#216e39", "FOURTH_QUARTILE"),
            }
            
            contribution_days = []
            total_contributions = 0
            
            for date_str, id_, level in days_matches:
                dt = datetime.strptime(date_str, "%Y-%m-%d")
                weekday = (dt.weekday() + 1) % 7
                
                color, level_name = level_map.get(level, ("#ebedf0", "NONE"))
                
                tooltip = tooltip_map.get(id_, "")
                count = 0
                count_match = re.search(r'(\d+) contribution', tooltip)
                if count_match:
                    count = int(count_match.group(1))
                elif "No contributions" in tooltip:
                    count = 0
                else:
                    count = int(level) * 3 if level != "0" else 0
                    
                total_contributions += count
                
                contribution_days.append({
                    "contributionCount": count,
                    "color": color,
                    "date": date_str,
                    "contributionLevel": level_name,
                    "weekday": weekday
                })
                
            # Sort chronologically by date
            contribution_days.sort(key=lambda d: d["date"])
            
            weeks = []
            current_week = []
            for day in contribution_days:
                current_week.append(day)
                if day["weekday"] == 6:
                    weeks.append({"contributionDays": current_week})
                    current_week = []
            if current_week:
                weeks.append({"contributionDays": current_week})
                
            response_data = {
                "data": {
                    "user": {
                        "contributionsCollection": {
                            "contributionCalendar": {
                                "totalContributions": total_contributions,
                                "weeks": weeks
                            }
                        }
                    }
                }
            }
            
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
            print("Successfully returned contribution calendar mock response!")
            
        except Exception as e:
            print(f"Error handling graphql: {e}")
            self.send_response(500)
            self.end_headers()
            self.wfile.write(str(e).encode('utf-8'))

def run_server():
    server_address = ('127.0.0.1', 443)
    httpd = http.server.HTTPServer(server_address, MockGraphQLHandler)
    
    # Wrap in SSL using python's built-in ssl module
    # We will use key.pem and cert.pem generated by openssl
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(certfile="cert.pem", keyfile="key.pem")
    httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
    
    print("Starting mock GraphQL server on port 443...")
    httpd.serve_forever()

if __name__ == "__main__":
    run_server()
